"""
api/app.py
──────────
Phase F: FastAPI application.

Exposes the stored entry-level job listings over HTTP so that any downstream
consumer (frontend, browser extension, mobile app) can query them without
touching the database directly.

Usage
─────
    uvicorn api.app:app --host 0.0.0.0 --port 8000 --reload

Endpoints
─────────
    GET  /health                Liveness check + DB reachability
    GET  /jobs                  Paginated, filterable job list
    GET  /jobs/{platform}/{id}  Single job detail

Interactive docs (auto-generated by FastAPI):
    http://localhost:8000/docs   – Swagger UI
    http://localhost:8000/redoc  – ReDoc
"""

from contextlib import asynccontextmanager

from fastapi import FastAPI
from sqlalchemy import text

from database.engine import get_session_factory, init_db

from .routes import router
from .schemas import HealthResponse
from .ui import ui_router


# ---------------------------------------------------------------------------
# Lifespan: create tables once at startup (no-op if already exist)
# ---------------------------------------------------------------------------

@asynccontextmanager
async def lifespan(app: FastAPI):  # type: ignore[type-arg]
    await init_db()
    yield


# ---------------------------------------------------------------------------
# Application
# ---------------------------------------------------------------------------

app = FastAPI(
    title="Student Job Curator",
    description=(
        "Entry-level and internship listings curated from Greenhouse and Lever "
        "job boards, filtered by a two-stage regex + LLM pipeline."
    ),
    version="1.0.0",
    lifespan=lifespan,
)

app.include_router(ui_router)   # serves GET / (dashboard)
app.include_router(router)      # serves GET /jobs, GET /jobs/{platform}/{id}


# ---------------------------------------------------------------------------
# Health check
# ---------------------------------------------------------------------------

@app.get("/health", response_model=HealthResponse, tags=["meta"])
async def health() -> HealthResponse:
    """Verify the API is running and the database is reachable."""
    db_status = "ok"
    try:
        session_factory = get_session_factory()
        async with session_factory() as session:
            await session.execute(text("SELECT 1"))
    except Exception:
        db_status = "unreachable"

    return HealthResponse(status="ok", database=db_status)
